name: Build LaTeX document
on:
  push:
    tags:
      - 'v*' # Run only on version tags

jobs:
  build_latex:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed for creating releases
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: dante-ev/latex-action@latest
        with:
          root_file: DynamicalBook.tex
          working_directory: book
          args: -pdf -latexoption=-file-line-error -latexoption=-interaction=nonstopmode -latexoption=-shell-escape
          extra_system_packages: python3-pygments
        continue-on-error: true

      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ steps.get_version.outputs.VERSION }}
          files: book/DynamicalBook.pdf
          draft: false
          prerelease: false
